@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Container(containerAlias, "Label", "Technology", "Optional Description")
Container_Ext(containerExtAlias, "Label", "Technology", "Optional Description")
ContainerDb(containerDbAlias, "Label", "Technology", "Optional Description")
ContainerDb_Ext(containerDbExtAlias, "Label", "Technology", "Optional Description")
ContainerQueue(containerQueueAlias, "Label", "Technology", "Optional Description")
ContainerQueue_Ext(containerQueueExtAlias, "Label", "Technology", "Optional Description")
@enduml